In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation

one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[9526, 3301, 4126, 151],
 [9526, 3301, 4126, 10],
 [9526, 1757, 4126, 8409],
 [8796, 3917, 8020, 443, 883],
 [8796, 3917, 8020, 443, 6502],
 [8623, 9526, 4035, 4126, 8714],
 [4339, 2882, 5297, 443]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9526 3301 4126  151]
 [   0    0    0    0 9526 3301 4126   10]
 [   0    0    0    0 9526 1757 4126 8409]
 [   0    0    0 8796 3917 8020  443  883]
 [   0    0    0 8796 3917 8020  443 6502]
 [   0    0    0 8623 9526 4035 4126 8714]
 [   0    0    0    0 4339 2882 5297  443]]


In [18]:
## feature representation
dim=10

In [24]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [25]:
input_shape = (None, sent_length)
model.build(input_shape)

In [26]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step


array([[[-0.04968823,  0.03336375,  0.01523516, -0.0092761 ,
         -0.00315367,  0.01137487, -0.00501585, -0.03993259,
         -0.00746585,  0.01780948],
        [-0.04968823,  0.03336375,  0.01523516, -0.0092761 ,
         -0.00315367,  0.01137487, -0.00501585, -0.03993259,
         -0.00746585,  0.01780948],
        [-0.04968823,  0.03336375,  0.01523516, -0.0092761 ,
         -0.00315367,  0.01137487, -0.00501585, -0.03993259,
         -0.00746585,  0.01780948],
        [-0.04968823,  0.03336375,  0.01523516, -0.0092761 ,
         -0.00315367,  0.01137487, -0.00501585, -0.03993259,
         -0.00746585,  0.01780948],
        [ 0.00394559,  0.02366999,  0.00482005,  0.04929808,
          0.02348298, -0.0311017 , -0.00978403, -0.04712277,
         -0.04783163, -0.02372084],
        [-0.02732231, -0.00194281,  0.04370458,  0.04335452,
          0.02632995, -0.00928289, -0.04164773, -0.03376972,
          0.04368259, -0.02024379],
        [-0.01061817,  0.04261352,  0.04553682, -0.0

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 9526, 3301, 4126,  151], dtype=int32)

In [31]:
model.predict(embedded_docs[0].reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[[-0.04968823,  0.03336375,  0.01523516, -0.0092761 ,
         -0.00315367,  0.01137487, -0.00501585, -0.03993259,
         -0.00746585,  0.01780948],
        [-0.04968823,  0.03336375,  0.01523516, -0.0092761 ,
         -0.00315367,  0.01137487, -0.00501585, -0.03993259,
         -0.00746585,  0.01780948],
        [-0.04968823,  0.03336375,  0.01523516, -0.0092761 ,
         -0.00315367,  0.01137487, -0.00501585, -0.03993259,
         -0.00746585,  0.01780948],
        [-0.04968823,  0.03336375,  0.01523516, -0.0092761 ,
         -0.00315367,  0.01137487, -0.00501585, -0.03993259,
         -0.00746585,  0.01780948],
        [ 0.00394559,  0.02366999,  0.00482005,  0.04929808,
          0.02348298, -0.0311017 , -0.00978403, -0.04712277,
         -0.04783163, -0.02372084],
        [-0.02732231, -0.00194281,  0.04370458,  0.04335452,
          0.02632995, -0.00928289, -0.04164773, -0.03376972,
          0.04368259, -0.02024379],
        [-0.01061817,  0.04261352,  0.04553682, -0.0